
const countries = [
    { name: "Afghanistan", code: "AF", phone: 93 },
    { name: "Afrique du Sud", code: "ZA", phone: 27 },
    { name: "Albanie", code: "AL", phone: 355 },
    { name: "Algérie", code: "DZ", phone: 213 },
    { name: "Allemagne", code: "DE", phone: 49 },
    { name: "Andorre", code: "AD", phone: 376 },
    { name: "Angola", code: "AO", phone: 244 },
    { name: "Anguilla", code: "AI", phone: 1264 },
    { name: "Arabie Saoudite", code: "SA", phone: 966 },
    { name: "Argentine", code: "AR", phone: 54 },
    { name: "Arménie", code: "AM", phone: 374 },
    { name: "Aruba", code: "AW", phone: 297 },
    { name: "Australie", code: "AU", phone: 61 },
    { name: "Autriche", code: "AT", phone: 43 },
    { name: "Azerbaïdjan", code: "AZ", phone: 994 },
    { name: "Bahamas", code: "BS", phone: 1242 },
    { name: "Bahrein", code: "BH", phone: 973 },
    { name: "Bangladesh", code: "BD", phone: 880 },
    { name: "Barbade", code: "BB", phone: 1246 },
    { name: "Belgique", code: "BE", phone: 32 },
    { name: "Bélize", code: "BZ", phone: 501 },
    { name: "Bénin", code: "BJ", phone: 229 },
    { name: "Bermudes", code: "BM", phone: 1441 },
    { name: "Bhoutan", code: "BT", phone: 975 },
    { name: "Bolivie", code: "BO", phone: 591 },
    { name: "Bosnie-Herzégovine", code: "BA", phone: 387 },
    { name: "Botswana", code: "BW", phone: 267 },
    { name: "Brésil", code: "BR", phone: 55 },
    { name: "Brunéi", code: "BN", phone: 673 },
    { name: "Bulgarie", code: "BG", phone: 359 },
    { name: "Burkina Faso", code: "BF", phone: 226 },
    { name: "Burundi", code: "BI", phone: 257 },
    { name: "Cambodge", code: "KH", phone: 855 },
    { name: "Cameroun", code: "CM", phone: 237 },
    { name: "Canada", code: "CA", phone: 1 },
    { name: "Chili", code: "CL", phone: 56 },
    { name: "Chine", code: "CN", phone: 86 },
    { name: "Chypre", code: "CY", phone: 357 },
    { name: "Colombie", code: "CO", phone: 57 },
    { name: "Comores", code: "KM", phone: 269 },
    { name: "Congo", code: "CG", phone: 242 },
    { name: "Congo, République démocratique du", code: "CD", phone: 243 },
    { name: "Cook, Iles", code: "CK", phone: 682 },
    { name: "Corée du Sud", code: "KR", phone: 82 },
    { name: "Corée du Nord", code: "KP", phone: 850 },
    { name: "Costa Rica", code: "CR", phone: 506 },
    { name: "Côte d'Ivoire", code: "CI", phone: 225 },
    { name: "Croatie", code: "HR", phone: 385 },
    { name: "Cuba", code: "CU", phone: 53 },
    { name: "Curaçao", code: "CW", phone: 599 },
    { name: "Danemark", code: "DK", phone: 45 },
    { name: "Djibouti", code: "DJ", phone: 253 },
    { name: "Dominicaine, République", code: "DO", phone: 1 },
    { name: "Dominique", code: "DM", phone: 1767 },
    { name: "Egypte", code: "EG", phone: 20 },
    { name: "Emirats arabes unis", code: "AE", phone: 971 },
    { name: "Equateur", code: "EC", phone: 593 },
    { name: "Erythrée", code: "ER", phone: 291 },
    { name: "Espagne", code: "ES", phone: 34 },
    { name: "Estonie", code: "EE", phone: 372 },
    { name: "Etats-Unis d'Amérique", code: "EU", phone: 1 },
    { name: "Ethiopie", code: "ET", phone: 251 },
    { name: "Féroé, îles", code: "FO", phone: 298 },
    { name: "Fidji", code: "FJ", phone: 679 },
    { name: "Finlande", code: "FI", phone: 358 },
    { name: "France", code: "FR", phone: 33 },
    { name: "Gabon", code: "GA", phone: 241 },
    { name: "Gambie", code: "GM", phone: 220 },
    { name: "Géorgie", code: "GE", phone: 995 },
    { name: "Ghana", code: "GH", phone: 233 },
    { name: "Grèce", code: "GR", phone: 30 },
    { name: "Grenade", code: "GD", phone: 1473 },
    { name: "Groenland", code: "GL", phone: 299 },
    { name: "Guadeloupe", code: "GP", phone: 590 },
    { name: "Guam", code: "GU", phone: 1671 },
    { name: "Guatemala", code: "GT", phone: 502 },
    { name: "Guinée", code: "GN", phone: 224 },
    { name: "Guinée-Bissau", code: "GW", phone: 245 },
    { name: "Guinée équatoriale", code: "GQ", phone: 240 },
    { name: "Guyana", code: "GY", phone: 592 },
    { name: "Guyane française", code: "GF", phone: 594 },
    { name: "Haïti", code: "HT", phone: 509 },
    { name: "Honduras", code: "HN", phone: 504 },
    { name: "Hong Kong", code: "HK", phone: 852 },
    { name: "Hongrie", code: "HU", phone: 36 },
    { name: "Inde", code: "IN", phone: 91 },
    { name: "Indonésie", code: "ID", phone: 62 },
    { name: "Iran'", code: "IR", phone: 98 },
    { name: "Iraq", code: "IQ", phone: 964 },
    { name: "Irlande", code: "ER", phone: 353 },
    { name: "Islande", code: "IS", phone: 354 },
    { name: "Israël", code: "IL", phone: 972 },
    { name: "Italie", code: "IT", phone: 39 },
    { name: "Jamaïque", code: "JM", phone: 1876 },
    { name: "Japon", code: "JP", phone: 81 },
    { name: "Jersey", code: "JE", phone: 44 },
    { name: "Jordanie", code: "JO", phone: 962 },
    { name: "Kazakhstan", code: "KZ", phone: 997 },
    { name: "Kenya", code: "KE", phone: 254 },
    { name: "Kirghizistan", code: "KG", phone: 996 },
    { name: "Kiribati", code: "KI", phone: 686 },
    { name: "Koweït", code: "KW", phone: 965 },
    { name: "Laos", code: "LA", phone: 856 },
    { name: "Lesotho", code: "LS", phone: 266 },
    { name: "Lettonie", code: "LV", phone: 371 },
    { name: "Liban", code: "LB", phone: 961 },
    { name: "Libéria", code: "LR", phone: 231 },
    { name: "Libye", code: "LY", phone: 218 },
    { name: "Liechtenstein", code: "LI", phone: 423},
    { name: "Lituanie", code: "LT", phone: 370 },
    { name: "Luxembourg", code: "LU", phone: 352 },
    { name: "Macao", code: "MO", phone: 853 },
    { name: "Macédoine du Nord", code: "MK", phone: 389 },
    { name: "Madagascar", code: "MG", phone: 261 },
    { name: "Malaisie", code: "MY", phone: 60 },
    { name: "Malawi", code: "MW", phone: 265 },
    { name: "Maldives", code: "MV", phone: 960 },
    { name: "Mali", code: "ML", phone: 223 },
    { name: "Malte", code: "MT", phone: 356 },
    { name: "Mariannes du nord", code: "MP", phone: 1670 },
    { name: "Maroc", code: "MA", phone: 212 },
    { name: "Marshall", code: "MH", phone: 692 },
    { name: "Martinique", code: "MQ", phone: 596 },
    { name: "Maurice", code: "MU", phone: 230 },
    { name: "Mauritanie", code: "MR", phone: 222 },
    { name: "Mayotte", code: "YT", phone: 262 },
    { name: "Mexique", code: "MX", phone: 52 },
    { name: "Micronésie, Etats Fédérés de", code: "FM", phone: 691 },
    { name: "Moldova, République de", code: "MD", phone: 373 },
    { name: "Monaco", code: "MC", phone: 377 },
    { name: "Mongolie", code: "MN", phone: 976 },
    { name: "Monténégro", code: "ME", phone: 382 },
    { name: "Montserrat", code: "MS", phone: 1664 },
    { name: "Mozambique", code: "MZ", phone: 258 },
    { name: "Namibie", code: "NA", phone: 264 },
    { name: "Nauru", code: "NR", phone: 674 },
    { name: "Népal", code: "NP", phone: 977 },
    { name: "Nicaragua", code: "NI", phone: 505 },
    { name: "Niger", code: "NE", phone: 227 },
    { name: "Nigéria", code: "NG", phone: 234 },
    { name: "Niue", code: "NU", phone: 683 },
    { name: "Norvège", code: "NO", phone: 47 },
    { name: "Nouvelle-Calédonie", code: "NC", phone: 687 },
    { name: "Nouvelle-Zélande", code: "NZ", phone: 64 },
    { name: "Oman", code: "OM", phone: 968 },
    { name: "Ouganda", code: "UG", phone: 256 },
    { name: "Ouzbékistan", code: "UZ", phone: 998 },
    { name: "Pakistan", code: "PK", phone: 92 },
    { name: "Palaos", code: "PW", phone: 680 },
    { name: "Palestine", code: "PS", phone: 970 },
    { name: "Panama", code: "PA", phone: 507 },
    { name: "Papouasie-Nouvelle-Guinée", code: "PG", phone: 675 },
    { name: "Paraguay", code: "PY", phone: 595 },
    { name: "Pays-Bas", code: "NL", phone: 31 },
    { name: "Pérou", code: "PE", phone: 51 },
    { name: "Philippines", code: "PH", phone: 63 },
    { name: "Pologne", code: "PL", phone: 48 },
    { name: "Polynésie française", code: "PF", phone: 689 },
    { name: "Porto Rico", code: "PR", phone: 1 },
    { name: "Portugal", code: "PT", phone: 351 },
    { name: "Qatar", code: "QA", phone: 974 },
    { name: "Réunion", code: "RE", phone: 262 },
    { name: "Roumanie", code: "RO", phone: 40 },
    { name: "Royaume-Uni", code: "GB", phone: 44 },
    { name: "Russie", code: "RU", phone: 7 },
    { name: "Rwanda", code: "RW", phone: 250 },
    { name: "Sahara occidental", code: "EH", phone: 967 },
    { name: "Saint-Barthélemy", code: "BL", phone: 967 },
    { name: "Saint-Kitts-et-Nevis", code: "KN", phone: 967 },
    { name: "Saint-Marin", code: "SM", phone: 967 },
    { name: "Saint-Martin (partie française)", code: "MF", phone: 967 },
    { name: "Saint-Martin (partie néerlandaise)", code: "SX", phone: 967 },
    { name: "Saint-Pierre-et-Miquelon", code: "PM", phone: 967 },
    { name: "Saint-Siège", code: "VA", phone: 967 },
    { name: "Saint-Vincent-et-les-Grenadines", code: "VC", phone: 967 },
    { name: "Sainte-Hélène, Ascension et Tristan da Cunha", code: "SH", phone: 967 },
    { name: "Sainte-Lucie", code: "LC", phone: 967 },
    { name: "Salomon, Iles", code: "SB", phone: 967 },
    { name: "Samoa", code: "WS", phone: 967 },
    { name: "Samoa américaines", code: "AS", phone: 967 },
    { name: "Sao Tomé-et-Principe", code: "ST", phone: 967 },
    { name: "Sénégal", code: "SN", phone: 967 },
    { name: "Serbie", code: "RS", phone: 967 },
    { name: "Seychelles", code: "SC", phone: 967 },
    { name: "Sierra Leone", code: "SL", phone: 967 },
    { name: "Singapour", code: "SG", phone: 967 },
    { name: "Slovaquie", code: "SK", phone: 967 },
    { name: "Slovénie", code: "SI", phone: 967 },
    { name: "Somalie", code: "SO", phone: 967 },
    { name: "Soudan", code: "SD", phone: 967 },
    { name: "Soudan du Sud", code: "SS", phone: 967 },
    { name: "Sri Lanka", code: "LK", phone: 967 },
    { name: "Suède", code: "SE", phone: 967 },
    { name: "Suisse", code: "CH", phone: 967 },
    { name: "Suriname", code: "SR", phone: 967 },
    { name: "Svalbard et île Jan Mayen", code: "SJ", phone: 967 },
    { name: "Swaziland", code: "SZ", phone: 967 },
    { name: "Tadjikistan", code: "TJ", phone: 967 },
    { name: "Taïwan, Province de Chine", code: "TW", phone: 967 },
    { name: "Tanzanie", code: "TZ", phone: 967 },
    { name: "Tchad", code: "TD", phone: 967 },
    { name: "Tchécoslovaquie", code: "CS", phone: 967 },
    { name: "Tchèque, République", code: "SZ", phone: 967 },
    { name: "Terres australes françaises", code: "TF", phone: 967 },
    { name: "Thaïlande", code: "TH", phone: 967 },
    { name: "Timor-Leste", code: "TL", phone: 967 },
    { name: "Togo", code: "TG", phone: 967 },
    { name: "Tokelau", code: "TK", phone: 967 },
    { name: "Tonga", code: "TO", phone: 967 },
    { name: "Trinité-et-Tobago", code: "TT", phone: 967 },
    { name: "Tunisie", code: "TN", phone: 967 },
    { name: "Turkménistan", code: "TM", phone: 967 },
    { name: "Turks-et-Caïcos (Îles)", code: "TC", phone: 967 },
    { name: "Turquie", code: "TR", phone: 967 },
    { name: "Tuvalu", code: "TV", phone: 967 },
    { name: "Ukraine", code: "UA", phone: 967 },
    { name: "URSS", code: "SU", phone: 967 },
    { name: "Uruguay", code: "UY", phone: 967 },
    { name: "Vanuatu", code: "VU", phone: 967 },
    { name: "Vatican", code: "VA", phone: 379 },
    { name: "Venezuela", code: "VE", phone: 967 },
    { name: "Viet Nam", code: "VN", phone: 967 },
    { name: "Viet Nam (Sud)", code: "VD", phone: 967 },
    { name: "Wallis et Futuna", code: "WF", phone: 967 },
    { name: "Yémen", code: "YE", phone: 967 },
    { name: "Yougoslavie", code: "YU", phone: 967 },
    { name: "Zambie", code: "ZM", phone: 967 },
    { name: "Zimbabwe", code: "ZW", phone: 967 }

];

// Assurez-vous que select_box est correctement défini
const select_box = document.querySelector('.options'),
    search_box = document.querySelector('.search-box'),
    input_box = document.querySelector('input[type="tel"]'),
    selected_option = document.querySelector('.selected-option div');


 let options = null;

// Utilisez forEach avec le tableau countries
countries.forEach(country => {
    const option = `
        <li class="option">
            <div>
                <span class="iconify" data-icon="flag:${country.code.toLowerCase()}-4x3"></span>
                <span class="county-name">${country.name}</span>
            </div>
            <strong>+${country.phone}</strong>
        </li>
    `;

    select_box.querySelector('ol').insertAdjacentHTML('beforeend', option);
    options = document.querySelectorAll('.option');
});

function selectOption(){
    console.log(this);
    const icon = this.querySelector('.iconify').cloneNode(true),
        phone_code = this.querySelector('strong').cloneNode(true);

    selected_option.innerHTML = '';
    selected_option.append(icon, phone_code);

    //mettre le code du pays dans le champs de saisi
    input_box.value = phone_code.innerText;
    //desactiver l'affichage des pays après avoir selectionner votre pays
    select_box.classList.remove('active');
    selected_option.classList.remove('active');
}

selected_option.addEventListener('click', () => {
    select_box.classList.toggle('active');
    selected_option.classList.toggle('active');
});

options.forEach(option=>option.addEventListener('click', selectOption));
